import Foundation

/// Controls haptic feedback generated by the marquee.
///
/// ```swift
/// MarqueeText("Incoming alert")
///     .haptics(.loop)
/// ```
public enum MarqueeHaptics: Sendable {
    /// No haptic feedback.
    case none
    /// A subtle impact occurs each time the content loops.
    case loop
    /// An impact occurs when content exits on either edge.
    case edge
    /// Both loop and edge feedback.
    case full
}
